### PR TITLE
feat: Added badges for test

### LINKED ISSUE #4: Add badges to README.

### PR DESCRIPTION
**Pull request by rushitote**
fix: #4

### CODE REVIEW

**Comment by hsluoyz** [comment]
@rushitote what about code coverage and release badges?

**Comment by rushitote** [comment]
@hsluoyz I can add semantic release but code coverage isn't possible currently for this plugin since the tests are using direct HTTP requests to the server and hence we only check the response.

**Comment by hsluoyz** [comment]
OK.

**Comment by hsluoyz** [comment]
@rushitote plz fix: https://github.com/casbin-lua/kong-authz/runs/3105673633?check_suite_focus=true

**Comment by rushitote** [comment]
fixed by a re-run.

**Pull request merged**
